### ISSUE TITLE
Add notifications for incoming reviews and CLs requiring attention.

### ISSUE THREAD

**Issue by davidgreenaway** [sdefresne/gerrit-monitor#12]
When I get sent a review, I like to respond to it as quickly as possible to unblock the CL author. Currently, Gerrit Monitor will display a red badge when there is an incoming review, but I often don't see it for quite some time.

It would be nice if Gerrit Monitor could display a browser/desktop notification when an incoming review comes in. It probably also makes sense to show notifications when a CL requires attention, so that I can address reviewer feedback and get my CL unblocked as quickly as possible.

Different users will presumably have different workflows and preferences, so which notifications are sent (if any) should ideally be configurable.

I'm happy to attempt to contribute this, if such a feature is considered desirable.

**Comment by sdefresne** [comment]
I planned to add such notifications when creating the extension. I decided not to implement it after discussion with the team managing the gerrit installation of Chromium as they told me they had plan to support notification from the website.

However, the discussion happened more than a year ago and there is still no support for notifications on the website. So I think it would be worthwhile to add support for notifications to the extension.

As a prerequisite for implementing notification, we need to change the background page to store information about the state of the CLs to review (currently state is discarded after the state of the badge is updated). This will be required to avoid spamming the user with notifications every time data is fetched from the server (currently every five minutes).

This change would bring the following two additional benefits:
- displaying the popup would be instantaneous (currently all information is fetched again)
- implementing "not my turn" would become possible.

Finally, I think such support should be configurable. At least globally, but maybe also per-repository.

**Comment by JoeyScarr** [comment]
Agreed that this feature would be incredibly useful. I have this extension installed but pretty much forget it exists because it doesn't notify me.
