### ISSUE TITLE
Feature Request: Flag reviews with new patchsets

### ISSUE THREAD

**Issue by loadedsith** [sdefresne/gerrit-monitor#14]
Hello,

For Sylvain: This issue relates to an email thread with the subject: "Gerrit Monitor - Extension: Feature Request: Flag reviews with new patchsets".

For everyone else, a paraphrased version of that thread;

A few reviews have not been flagged as incoming in this extension, resulting in a failure to review in a timely manner.

Looking at these instances it seems that the reason is someone pushes a patchset and expects the review to continue from there, but the extension triggers the incoming state on a new comment. I've noticed the Gerrit dashboard considers a review incoming when it has a new patchset.

Working directly with my team(s) I could easily ask them to comment back, but I also work with outside teams who change regularly. Unfortunately, telling them to send these comments would not be applied universally.

I wouldn't want my review sent out just because I uploaded a patchset. Perhaps this feature could be configurable (ideally per host)?

**Comment by sdefresne** [comment]
This should be fixed in 1.0.5 (at least, I think the CL linked fixes the issue).

**Comment by sdefresne** [comment]
This should be fixed in 1.0.5 (at least, I think the CL linked fixes the issue).

**Comment by loadedsith** [comment]
Thanks!
