### ISSUE TITLE
"Mark reviewed" CLs should not require attention

### ISSUE THREAD

**Issue by anp** [sdefresne/gerrit-monitor#15]
Hi! Super useful. Ideally CLs that I have [marked as reviewed](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#mark-as-reviewed) would disappear from the extension's list.

**Comment by satayev** [comment]
It'd be nice to have a "mark as reviewed"  button in the extension window as well.

**Comment by sdefresne** [comment]
This should be fixed by pull request #22.
