### ISSUE TITLE
Periodic updates don't seem to be working

### ISSUE THREAD

**Issue by chuim** [sdefresne/gerrit-monitor#23]
It seems that the periodic updates that should make the extension icon show actionable CLs are not working for me. I have the impression that it is only updating when I actually press the extension icon and force a refresh.

**Comment by sdefresne** [comment]
I am unable to reproduce. I see the periodic updates happening every five minutes as expected when I inspect the background page (navigate to chrome://extensions > search for Gerrit Monitor > clic Details > Inspect views > background.html).

Can you check whether the periodic updates occur or not in your case. Also are you on stable version of Chrome or another version (maybe there were changes in Chrome that broke the periodic update).
