### ISSUE TITLE
Change the sorting order for CLs

### ISSUE THREAD

**Issue by nfischer** [sdefresne/gerrit-monitor#27]
Gerrit-monitor sometimes shows new CLs in the middle or at the end of my list of "incoming CLs requiring your attention." This isn't ideal for me because I have some CLs in that list that I don't expect will be cleared any time soon (the authors probably won't pursue these CLs further, but that's aside from the point). It would work better for me if gerrit-monitor sorted by last-modified timestamp (more-recently modified CLs are at the top, stale CLs are at the bottom), so I could work from top to bottom (and stop when I get to the stale CLs).

I should also mention I use several gerrit instances. I'm not sure if this kind of sorting is already being applied within each gerrit instance, but I would prefer for it to be applied _across all_ instances (ex. I don't want fresh chromium CLs to be sorted below stale Android CLs).

**Comment by loadedsith** [comment]
I'll +1 the first part: I just noticed today for the first time that the order wasn't predictable. I had 2 new cr's: first I clicked the one in the first slot, and then immediately opened the window again and clicked the item in the second slot, but it was the same review.

**Comment by sdefresne** [comment]
Currently the CLs are grouped by host, and for each host, the CLs are sorted in the order returned by the query with the host. I agreed that sorting them should probably be a good idea. I'll see what I can do about that. Sorting by "last modification date" may not work for @loadedsith use case as the order may change between two access to the popup (if someone just commented between the two accesses) but it looks like what @nfischer is asking. In fact, I think this is already the order used by the server when they return the list of CLs.

I'm wondering whether the "attention set" support added with #30 could help with initial request by @nfischer (as you can remove yourself from the "attention set" for CLs that you think are stale). Then we can sort the CLs by (host, id) tuple which will be stable between all access to the popup.

Would "attention set" + stable order work for both of your requests?

**Comment by loadedsith** [comment]
FWIW I’m at a new company and no longer use this extension or Gerrit at all. Have at it. I’m gonna unsub too, have a good one!

**Comment by nfischer** [comment]
Ah, I didn't realize the attention set support shipped! I just turned it on and it's a big improvement for my case.

I think sorting by last modification date would still help me work through CLs in a reasonable order, but it's not high priority if it's difficult to implement.
