### ISSUE TITLE
[Feature] Bulk open reviews

### ISSUE THREAD

**Issue by loadedsith** [sdefresne/gerrit-monitor#28]
Pretty often in the morning I open my queue, have 5-10 reviews, and would like to open them all. 

If it helps, now I open the window, right click inspect and run this command in the console: 

`[...document.querySelectorAll('.incomingRequiringAttention .changelistheader')].forEach((e)=>{e.click()})`

And that seems to work ok, but it'd a nice to have a button that does the same.

Thanks,

**Comment by hanwen** [comment]
alternate, but related request: when I come in in the morning, I often get barraged with a set of notifications. It would be great to not have to click 10 times to make them go away.
