### ISSUE TITLE
FR: Support attention set

### ISSUE THREAD

**Issue by Carrotman42** [sdefresne/gerrit-monitor#30]
Gerrit's [new attention set feature](https://www.gerritcodereview.com/design-docs/attention-set-use-cases.html) is quite useful: it helps ensure everyone communicates who they think needs to do some action on a CL. This can work quite well in conjunction with this monitor extension in that the extension could use this information to decide whether some CL is "important" to someone at any given moment.

I didn't see an issue tracking the adoption of this information in the list, but apologies if I simply missed it!

**Comment by jkopczyn** [comment]
My team (Chrome Infra) has a work freeze for all our normal codebases for most of December, so I'm going to take a crack at this if Sylvain hasn't.

**Comment by sdefresne** [comment]
A new version with the pull request #31 has been uploaded to the store and should eventually become available (it is in review, which may take longer than usual due to the end of year celebration). Once version 1.1.2 is available, could you check whether it works for you?

**Comment by Carrotman42** [comment]
Thanks to jkopczyn@ for the patch, and sdefresne@ for the ping. My extension has updated to version 1.1.2, but it doesn't appear to be working as I expect. Namely:

* I have two CLs under "Incoming CLs requiring your attention", each under the same gerrit host
* On the homepage for that host (e.g. `https://$HOSTNAME/dashboard/self`) I see the two CLs there under "Incoming Reviews"
* But I am in the attention set of only one of the CLs

Since I'm only in the attention set of one of the CLs, I'd expect to only see that one CL in the "Incoming CLs requiring your attention" section. Perhaps #32 ("attention-set-only" option) is needed for my expectation to be met?

**Comment by jkopczyn** [comment]
> Perhaps #32 ("attention-set-only" option) is needed for my expectation to be met?

Yes, that sounds correct. My regular work has resumed, and this is merely convenient rather than important to me, so I have not gotten around to patching the names in #32 and submitting it. The changes are fairly trivial so I expect anyone motivated could do so if they'd rather not wait on me. I'll probably get to it before February if not.

**Comment by Carrotman42** [comment]
Woohoo, thanks to everyone for their efforts here!
