### ISSUE TITLE
switch color & order of grant permission buttons for allow/deny

### ISSUE THREAD

**Issue by allysillins** [sdefresne/gerrit-monitor#36]
It took me 3 rounds of clicking the wrong button & having my permissions not be enabled before I realized that I was clicking the wrong button. I assumed the blue button was "Allow" and the white button was "Deny". I think this was due to both the colors and the order. I would have expected the left most button to be blue & "Allow" & the right side one to be white and "Deny". Would you consider swapping these around?

![Screenshot 2021-02-27 2 47 50 PM](https://user-images.githubusercontent.com/27468171/109402467-fad79b80-790a-11eb-95a5-a5e3bc57ab3b.png)

**Comment by sdefresne** [comment]
This dialog is presented by Chrome and not the extension itself. There is nothing that the extension itself can do.

You can try to report this as a bug against Chrome (https://crbug.com/) if you think that the dialog to grant permissions to an extension are not intuitive.
