### ISSUE TITLE
Ignored CLs should not require attention

### ISSUE THREAD

**Issue by agampe** [sdefresne/gerrit-monitor#5]
Gerrit allows to "ignore" CLs:

[REST API docs](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#ignore)

I have over a hundred of them (it's old CLs and my team is not in the business of abandoning external contributions). It would be nice if the "ignored" state would be taken into account for what is displayed.

**Comment by shali3** [comment]
+1

**Comment by sdefresne** [comment]
Version 1.0.2 has been pushed to the store with a fix included. It should take some time to update in your installation.
