### ISSUE TITLE
Unable to request permissions after move to manifest v3

### ISSUE THREAD

**Issue by emembrives** [sdefresne/gerrit-monitor#50]
Following #48, the [permissions to access to URLs changed](https://github.com/sdefresne/gerrit-monitor/commit/197eb6d2071107079111bac5b10355a131e31050#diff-6bc2c0b5164076a1b57b067398be19a40d2b8efa3428b03504562ea88593866cR22-R23). Since this version, however, I am unable to get Gerrit Monitor to work, as it asks me for permissions without any possibility to grant them.

It might seem that the issue lies in https://github.com/sdefresne/gerrit-monitor/blob/main/src/options.js#L201, which should use https://developer.chrome.com/docs/extensions/reference/permissions/#step-3-request-optional-permissions to request read permission on the origins, and not just notifications.

**Comment by sdefresne** [comment]
Duplicate issue #49.
