### ISSUE TITLE
Add a button to log in to all repositories

### ISSUE THREAD

**Issue by eyal0** [sdefresne/gerrit-monitor#6]
When I have multiple repos in gerrit-monitor and any of them is not signed in, I get a "Try loggin in" message with 4 links to click and I have to click all four of them, which is annoying.

Could we add a button that would click all the links?

**Comment by sdefresne** [comment]
I've pushed a new version that includes https://github.com/sdefresne/gerrit-monitor/pull/10. With this version, the extension will try to make a request to the server with CORS disabled which should allow the browser to follow the redirection to the authentication servers and hopefully refresh the authentication.

With this new version, it is possible that you won't see the "Try logging in" message and thus a button may not be necessary. Could you check when you have time whether the extension is now properly authenticating and not showing up the "Try logging in" error message.

If it is still displayed, I'll investigate how to add a button to open all the links (or all the links to the server that need re-authentication).

Thank you for your patience.

**Comment by eyal0** [comment]
I tested this on my corporate account and it works.  Thanks!

**Comment by eyal0** [comment]
I spoke to soon.  It isn't working for me.  :-(  Sorry.

How can I help debug this?

**Comment by eyal0** [comment]
My testing:

I click on the gerrit monitor and it says that I need to try logging in.  I have 4 different repos.

I click on the first, sign in, try the gerrit monitor again, same warning.

Click on the second, sign in, again, same warning.

Click on the third, etc, only after click on every single one individually does the gerrit monitor start working.

**Comment by eyal0** [comment]
It seems like only my laptop, which I got from my employer, it having a problem.  My desktop computer is fine.

**Comment by sdefresne** [comment]
This should be fixed in version 1.0.4 (which should be deployed soon).

**Comment by eyal0** [comment]
The new button looks good.  I find that sometimes I need to press the button, sometimes it isn't needed.  When I press it, it is effective.

Thanks for your efforts!
